name: Run Pytest on EC2

on:
  push:
    tags:
      - "run-tests-*"

jobs:
  run-tests-on-ec2:
    name: SSH to EC2 and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_key
          chmod 600 ec2_key

      - name: Run tests on EC2
        run: |
          echo "ðŸ”Ž Connexion Ã  lâ€™instance ec2-g4dn-xlarge (13.53.41.49)"
          ssh -o StrictHostKeyChecking=no -i ec2_key ubuntu@13.53.41.49 << 'EOF'
            set -e
            cd ~/mai25_CMLops/MAI25_CMLOps_Rakuten
            docker compose down
            ./generate_compose.sh --with-api
            echo "ðŸ” Starting containers..."
            docker compose up -d

            echo "â³ Sleeping to allow services to start..."
            sleep 10

            echo "ðŸ” Status des services"
            docker compose ps

            echo "ðŸ“œ Logs du service api (si plantÃ©)"
            docker compose logs api || true

            echo "âœ… Running tests..."
            docker compose exec -T api pytest tests/ --disable-warnings || {
              echo 'âŒ Tests failed'; exit 1;
            }

            echo "ðŸ§¹ Stopping containers..."
            docker compose down
          EOF